### ISSUE TITLE
navigation panel is not obvious on desktop browsers

### ISSUE THREAD

**Issue by jclulow** [omniosorg/omniosorg.github.io#10]
In mobile browsers, the site scales down very well to fit on small screens, hiding all of the navigation elements behind a "hamburger" icon in the top-left.  This is a well-established convention for small touch screen devices.

<img src="https://user-images.githubusercontent.com/304070/41378687-b3a1d88c-6f14-11e8-9f0a-06404e0a8b89.jpg" width="300">
<img src="https://user-images.githubusercontent.com/304070/41378688-b3c364b6-6f14-11e8-929d-ef8c7d8461f9.jpg" width="300">

Unfortunately it doesn't play out quite so well in a desktop browser, where the hamburger is comparatively hard to see -- especially now that there are specific textual links on the right to things like _Downloads_ and _Release Notes_.

<img src="https://user-images.githubusercontent.com/304070/41378912-6b7d3ba4-6f15-11e8-9a16-0b4eef8c9f93.png" width="500">

It might be worth replacing _Release Notes_ on the right with a _Documentation_ link that takes you to the full tree of documentation headings.  It might also be worth leaving the navigation panel expanded all the time on a desktop browser, or at least replacing the hamburger with a "Site Map" or "Documentation" textual link.

**Comment by oetiker** [comment]
thanks for the suggestions ... will try to add some better visibility to the menu on wide screen devices

**Comment by oetiker** [comment]
there is now a lable on the menu button 0219f3dc136167ac8b023c395cfb65de5ce1cdfd
