### ISSUE TITLE
Wrong link to PXE download

### ISSUE THREAD

**Issue by Mno-hime** [omniosorg/omniosorg.github.io#5]
I can't download kayak PXE from Download -> PXE link. It seems that here https://github.com/omniosorg/omniosorg.github.io/blob/6499b3d0b9dd05e071da40e37bc53dee6c52d590/_includes/header.html#L52 it should be _dash_ instead of _underscore_ in `kayak_{{site.omnios_stable}}`.

**Comment by oetiker** [comment]
thanks ... fixed in 39c5f8c uploading now

**Comment by Mno-hime** [comment]
Actually, **omniosce**-r151022s.zfs.bz2 file exists on the server but **kayak**-r151022s.zfs.bz2 is on the web, sorry for misleading you :). Not sure which file name is the right one.

**Comment by oetiker** [comment]
oops ... thanks ... I should have checked ... fixed again ... 5d98d03
